spring:
  application:
    name: weather-fetcher
  kafka:
    bootstrap-servers: "localhost:29092"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "order-2"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  datasource:
    password: super_password
    username: main_user
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: keys.yml
open-weather:
  key: ${secret.open-weather-key}
server:
  port: 8080
