spring:
  application:
    name: weather-fetcher
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    password: super_password
    username: main_user
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: optional:keys.yml
open-weather:
  key: ${OPEN_WEATHER_KEY:${secret.open-weather-key}}
server:
  port: 8082
