spring:
  application:
    name: weather-fetcher
  kafka:
    bootstrap-servers: "localhost:29092"
  datasource:
    password: super_password
    username: main_user
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: keys.yml
open-weather:
  key: ${secret.open-weather-key}
server:
  port: 8080
