spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: weather-tgbot
  datasource:
    username: main_user
    password: super_password
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: keys.yml
telegram:
  bot-key: ${secret.telegram-bot-key}
server:
  port: 8081