spring:
  application:
    name: weather-tgbot
  datasource:
    username: main_user
    password: super_password
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
  config:
    import: keys.yml
telegram:
  bot-key: ${secret.telegram-bot-key}
server:
  port: 8081