spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "order-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  application:
    name: weather-tgbot
  datasource:
    username: main_user
    password: super_password
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: keys.yml
telegram:
  bot-key: ${secret.telegram-bot-key}
server:
  port: 8081