spring:
  application:
    name: weather-tgbot
  datasource:
    username: main_user
    password: super_password
    url: jdbc:postgresql://localhost:5432/main_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  config:
    import: optional:keys.yml
telegram:
  bot-key: ${TELEGRAM_BOT_KEY:${secret.telegram-bot-key}}